### ISSUE TITLE
Not working with scala 3.1.0 and greater

### ISSUE THREAD

**Issue by keirlawson** [sbt/sbt-unidoc#155]
Changing the test scala version in the scala 3 test (and corresponding assertions) within this repo to 3.1.0 or greater causes the test to fail. I think this means unidoc is generally broken on later scala 3 versions?

**Comment by xuwei-k** [comment]
https://github.com/scala/scala3/commit/05f73107a916ee499c807b7f030535ea8df52714#diff-5bc061614284c365d3bcea5a600911cfc4d74e908be8d1c15bf5fb46f2e83957L33 🤔
