### ISSUE TITLE
warning: Supported source version less than target

### ISSUE THREAD

**Issue by JohnMurray** [sbt/sbt-unidoc#18]
Hello,

I'm not sure if this error belongs in this project or the genjavadoc project. I am getting an error that seems to state that annotations are processed with an assumed input source-version of Java 6 (just a guess). I tried using  a new version of the genjavadoc plugin (0.9) as well since the diff between 0.8 and 0.9 mentioned some Java 8 improvements, but I got the same error. I looked at both projects but I don't see any reference to the `susi` project that this seems to come from. Anyways, looking for some help to track down / resolve / work-around the issue.

```
[warn] warning: Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.sisu.space.SisuIndexAPT6' less than -source '1.8'
```

Thanks!
John Murray

**Comment by LucasDvp** [comment]
+1
