### ISSUE TITLE
Upgrade to genjavadoc 0.9

### ISSUE THREAD

**Issue by JohnMurray** [sbt/sbt-unidoc#22]
When I attempted to use scala version `2.11.7` I got an error because genjavadoc could not be found for that version. It seems they did not publish a `0.8` for `2.11.7` and only a `0.9`. It would be awesome if, by default, this project used `0.9`.

**Comment by ktoso** [comment]
Sounds like a good idea :+1: (/me somewhat contributing to genjavadoc)
