### ISSUE TITLE
unidoc compile issue

### ISSUE THREAD

**Issue by ghost** [sbt/sbt-unidoc#24]
Hi,

I am getting the below error while running sbt unidoc:
/Users/dhavalkolapkar/Documents/Workspace/Kamanja/trunk/EnvContexts/SimpleEnvContextImpl/src/main/scala/com/ligadata/SimpleEnvContextImpl/SimpleEnvContextImpl.scala:2105: type mismatch;
[error] found : (com.ligadata.KvBase.Key, com.ligadata.KvBase.Value) => Unit
[error] required: (com.ligadata.StorageBase.Key, com.ligadata.StorageBase.Value) => Unit
[error] dataStore.get(containerName, callbackFunction)
[error] ^
[error] /Users/dhavalkolapkar/Documents/Workspace/Kamanja/trunk/EnvContexts/SimpleEnvContextImpl/src/main/scala/com/ligadata/SimpleEnvContextImpl/SimpleEnvContextImpl.scala:2154: overloaded method value get with alternatives:
errorUnit

I have 15 sub projects and my build.sbt contains:
lazy val commonSettings = Seq(
scalaVersion := "2.11.4",
autoAPIMappings in unidoc := true
)

val root = (project in file(".")).settings(commonSettings: _).
settings(unidocSettings: _).
aggregate(subprojects)

**Comment by DhavalKolapkar** [comment]
@pvlugter Could you please help me out

**Comment by 2m** [comment]
Are you sure this is unidoc issue? Does running `compile` sbt task on the subproject that has `SimpleEnvContextImpl.scala` complete without errors?
