### ISSUE TITLE
autoAPIMappings does not seem to work with unidoc task

### ISSUE THREAD

**Issue by wookietreiber** [sbt/sbt-unidoc#5]
I have tried to get the sbt setting [autoAPIMappings](http://www.scala-sbt.org/0.13.2/docs/Howto/scaladoc.html#auto-link) to work with unidoc, unsuccessfully. I already tried the following settings:

```scala
autoAPIMappings := true

autoAPIMappings in unidoc := true

autoAPIMappings in ScalaUnidoc := true

autoAPIMappings in (ScalaUnidoc, unidoc) := true
```

Is it currently ignored or is this an *I am to stupid to use sbt* issue?

**Comment by taylorleese** [comment]
Similarly, it appears that ```apiMappings``` is not respected by unidoc as well.

**Comment by eed3si9n** [comment]
```
autoAPIMappings := true
```

should now work with sbt-unidoc 0.3.2.

**Comment by wookietreiber** [comment]
Awesome, thanks.
