### ISSUE TITLE
'xsbt ghpagesPushSite' failing with java unidoc: 'fatal: Not a git repository'

### ISSUE THREAD

**Issue by erikerlandson** [sbt/sbt-unidoc#58]
I have a smallish java project here:
https://github.com/erikerlandson/gibbous/tree/unidoc-issue

I attempted to set it up for generating javadoc per the instructions on your site. You can browse my sbt setup at the branch linked above.

`xsbt previewSite` seems to be generating what I expect, but `xsbt ghpagesPushSite` is failing in a strange way.  I have attached the full output, but the error is this:
```
[info] Loading settings from build.sbt ...
[info] Set current project to gibbous (in build file:/home/eje/git/gibbous/)
[error] fatal: Not a git repository (or any parent up to mount point /home)
```

[full output](https://github.com/sbt/sbt-unidoc/files/2087451/t.txt)

**Comment by 2m** [comment]
For me it looks like sbt-ghpages plugin got something that was unexpected (missing git repository). Therefore I am not sure if that is related to `sbt-unidoc`.

**Comment by erikerlandson** [comment]
I'm at a loss to guess what git repo could be missing. I executed `xsbt ghpagesPushSite` in my git repo.  It has a `gh-pages` branch constructed as usual.

**Comment by 2m** [comment]
I see that you are adding some mappings in your repo. And the sbt-ghpages plugin runs [some git commands](https://github.com/sbt/sbt-ghpages/blob/master/src/main/scala/com/typesafe/sbt/sbtghpages/GhpagesPlugin.scala#L54) depending of the mappings at least from my initial impressions. I would try digging there. :)

**Comment by erikerlandson** [comment]
Found a solution here: https://github.com/sbt/sbt-ghpages/issues/40
`~/.sbt/ghpages` was stale somehow.
