### ISSUE TITLE
Does unidoc support '<' and '>'?

### ISSUE THREAD

**Issue by phegstrom** [sbt/sbt-unidoc#61]
When building docs from scala docs in the Spark repository, I found that I couldn't use `>` or `<`, is there a way to escape these characters if they are supported?

```
> build/sbt unidoc
...
[error] ./spark/sql/core/target/java/org/apache/spark/sql/functions.java:2834: error: malformed HTML
[error]    *    limit < 0: <code>regex</code> will be applied as many times as possible, and the resulting
[error]               ^
```

**Comment by xuwei-k** [comment]
I think this is a [genjavadoc](https://github.com/lightbend/genjavadoc) issue, not sbt-unidoc.
