### ISSUE TITLE
Does unidoc support silencer

### ISSUE THREAD

**Issue by manuzhang** [sbt/sbt-unidoc#67]
It seems that https://github.com/ghik/silencer doesn't work with sbt-unidoc.

silencer version: 1.3.1
unidoc version: 0.4.2

**Comment by 2m** [comment]
I have not tried it, but it might be the case of using the correct scope, when adding silencer compiler plugin.

Have you tried:

```scala
ScalaUnidoc / unidoc / libraryDependencies ++=  Seq(
  compilerPlugin("com.github.ghik" %% "silencer-plugin" % silencerVersion),
  "com.github.ghik" %% "silencer-lib" % silencerVersion % Provided
)
```

**Comment by manuzhang** [comment]
Thanks, adding compiler dependency to unidoc settings works
