### ISSUE TITLE
Unidoc is broken on Scala 2.12.8

### ISSUE THREAD

**Issue by torkelrogstad** [sbt/sbt-unidoc#69]
I'm not able to generate functioning Scaladocs with Scala 2.12.8.

Here's a reproducible example: https://github.com/torkelrogstad/scaladoc-test

The generated docs in `target/scala-2.11/unidoc` work just fine. The ones in `scala-2.12` have broken relative links. You can reproduce this by doing `sbt unidoc`, and changing the Scala version in `build.sbt` on line 4.

**Comment by 2m** [comment]
Which links in particular do you have in mind?

I did a quick test and I wasn't able to spot any broken links. I cloned your repo and generated unidoc, which it did for scala 2.12.8 as that is the version in your repo and clicked around in the generated website.

**Comment by torkelrogstad** [comment]
Turns out this was because the app I used to serve the Scaladoc locally ([serve](https://www.npmjs.com/package/serve)) broke the links... Sorry about that! And thanks for replying

**Comment by 2m** [comment]
Ahh, I see. No problem!
